### ISSUE TITLE
component.service.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [Bryant-24/shop#2]
Не понял в чем суть этого метода
```

  getProducts(): Array<Product> {
    return [];
  }
```

**Comment by Bryant-24** [comment]
Спасибо за замечание, @VZhyrytskiy!

Это я пытался реализовать функционал вот этой задачи:
```
7. Создайте компонент (ng g c cart) и используйте его в AppComponent темплейте. 
Компонент должен отображать список купленых товаров. 
Организуйте список в виде отдельного сервиса - CartService.
```

Но теперь понял, что он так и остался неиспользуемым.

А как правильно в таком случае сделать?
- как сделано сейчас, то есть у нас есть просто свойство в `CartComponent`, в которое мы добавляем товары;
- или же в `CartService` создать пустой массив и возвращать из него продукты;

**Comment by VZhyrytskiy** [comment]
Я бы сделал второй вариант
